[package]
name = "win-channel"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "0.57.0", features = [ "Win32_Foundation", "Win32_System_Threading", "Win32_Security", "Win32_System_Memory", "Win32_System_WindowsProgramming", "Win32_System_SystemServices" ] }
